import { type SimplificationOptions } from './types'

export const noSimplify: SimplificationOptions = {
	removeDoubleNegatives: false,
	removeMinusFromZero: false,
	removeDoublePlusMinusSigns: false,

	turnFloatsIntoIntegers: false,
	factorizeIntegers: false,

	flattenSums: false,
	removePlusZeroFromSums: false,
	mergeSumNumbers: false,
	cancelSumTerms: false,
	groupSumTerms: false,
	expandMinusSums: false,
	expandPlusMinusSums: false,
	pullOutCommonSumNumbers: false,
	pullOutCommonSumFactors: false,
	sortSums: false,

	flattenProducts: false,
	mergeProductMinuses: false,
	mergeProductPlusMinuses: false,
	reduceProductsWithZero: false,
	removeTimesOneFromProducts: false,
	mergeProductNumbers: false,
	mergeProductFactors: false,
	expandProductsOfSums: false,
	expandProductsOfSumsWithinSums: false,
	sortProducts: false,

	reduceFractionsWithZeroNumerator: false,
	reduceFractionsWithOneDenominator: false,
	mergeFractionProducts: false,
	flattenFractions: false,
	mergeFractionSums: false,
	splitFractions: false,
	mergeFractionMinuses: false,
	mergeFractionNumbers: false,
	cancelFractionFactors: false,
	mergeFractionFactors: false,
	normalizeFractionMinuses: false,
	applyPolynomialCancellation: false,

	removeZeroExponentFromPowers: false,
	removeZeroBaseFromPowers: false,
	removeOneExponentFromPowers: false,
	removeOneBaseFromPowers: false,
	mergePowerMinuses: false,
	mergePowerNumbers: false,
	removePowersWithinPowers: false,
	removeNegativePowers: false,
	expandPowers: false,
	expandPowersOfProducts: false,
	expandPowersOfFractions: false,
	expandPowersOfSums: false,
	expandPowersOfSumsWithinSums: false,

	reduceRootsWithZeroArgument: false,
	reduceRootsWithOneArgument: false,
	reduceIntegerRoots: false,
	reduceCanceledRoots: false,
	turnRootsIntoFractionExponents: false,
	turnFractionExponentsIntoRoots: false,
	turnBaseTwoRootsIntoSqrts: false,
	turnSqrtsIntoBaseTwoRoots: false,
	expandRootsOfProducts: false,
	mergeProductsOfRoots: false,
	pullExponentsIntoRoots: false,
	pullFactorsOutOfRoots: false,
	preventRootDenominators: false,

	removeOneLogarithm: false,
	removeEqualBaseArgumentLogarithm: false,
	turnLogIntoLn: false,

	remove01TrigFunctions: false,
	removeRootTrigFunctions: false,
	turnTanIntoSinCos: false,
}
