export type { NumberLike, InterpolationValue, InterpolationPair, InterpolationGrid, InterpolationTableDefinition, InterpolationTable, TableInterpolationInput, TableInterpolationOutput } from './types'
export { isInterpolationTable, isValidInterpolationPart } from './checks'
export { getInterpolationPart, getClosestIndices } from './support'
export { rangeInterpolate } from './rangeInterpolation'
export { gridInterpolate } from './gridInterpolation'
export { createInterpolationTable, ensureInterpolationTable } from './tableCreation'
export { tableInterpolate, multiOutputTableInterpolate, inverseTableInterpolate } from './tableInterpolation'
