export { default as Home } from './Home'
export { default as Courses } from './Courses.js'
export { default as Course } from './Course.js'
export { default as Feedback } from './Feedback.js'
export { default as About } from './About.js'
export { default as History } from './History.js'
