version: '3'
services:
  gateway:
    build:
      context: ..
      dockerfile: ops/gateway/Dockerfile
      args:
        REACT_APP_API_ADDRESS: "https://api.step-wise.com"
        REACT_APP_API_WEBSOCKET_ENDPOINT: "graphql-ws"
        REACT_APP_GOOGLE_CLIENT_ID: "212013243072-slab3pojp2u1pirqfr5g7p78280l2b8q.apps.googleusercontent.com"
        REACT_APP_GOOGLE_REDIRECT_ADDRESS: "https://step-wise.com"
    image: stepwisecom/gateway:latest

  api:
    build:
      context: ..
      dockerfile: api/Dockerfile
    image: stepwisecom/api:latest
