version: '3'
services:
  shared:
    build: ../shared
    image: shared-build:latest
  frontend:
    build:
      context: ../frontend
      args:
        REACT_APP_API_ADDRESS: "https://api.step-wise.com"
        REACT_APP_API_WEBSOCKET_ENDPOINT: "graphql-ws"
        REACT_APP_GOOGLE_CLIENT_ID: "212013243072-slab3pojp2u1pirqfr5g7p78280l2b8q.apps.googleusercontent.com"
        REACT_APP_GOOGLE_REDIRECT_ADDRESS: "https://step-wise.com"
    depends_on:
      - shared
    image: frontend-build:latest
  gateway:
    build: gateway
    depends_on:
      - frontend
    image: stepwisecom/gateway:latest
  api:
    build: ../api
    depends_on:
      - shared
    image: stepwisecom/api:latest
