version: '3'
services:
  gateway:
    build: gateway
    restart: on-failure
    depends_on: [api]
    ports:
      - "80:80"
    logging:
      options:
        max-size: "100m"
        max-file: "10"
  api:
    build: ../api
    restart: on-failure
    environment:
      PORT: "80"
    expose:
      - "8080"
    logging:
      options:
        max-size: "100m"
        max-file: "10"
