version: '3'
services:
  nginx:
    image: nginx:1.18.0-alpine
    container_name: nginx
    restart: on-failure
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ../frontend/build:/www
    ports:
      - 80:80
