version: '3'
services:
  gateway:
    build: gateway
    hostname: gateway
    restart: on-failure
    depends_on: [api]
    ports:
      - "80:80"
    logging:
      options:
        max-size: "100m"
        max-file: "10"
  api:
    build: ../api
    hostname: api
    restart: on-failure
    env_file:
      - /config/api.env
    environment:
      PORT: "80"
      NODE_ENV: "production"
    expose:
      - "80"
    logging:
      options:
        max-size: "100m"
        max-file: "10"
