name: Continuous Integration
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Run all tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Setup test environment
        run: |
          sudo mkdir /config
          sudo touch /config/api.env
      - name: Build project
        run: |
          docker-compose -f ops/build.yml build
      - name: Run frontend tests
        run: docker run --rm -t -e CI=true frontend_build npm test
      - name: Run api tests
        run: docker run --rm -t stepwisecom/api npm test
      - name: Publish images
        # if: github.ref == 'refs/heads/master'
        env:
          DOCKER_REGISTRY_KEY: ${{ secrets.DOCKER_REGISTRY_KEY }}
        run: |
          docker login --username stepwisecom --password $DOCKER_REGISTRY_KEY
          docker image ls -f reference="stepwisecom/*" --format "{{.Repository}}" \
            xargs -n 1 docker push
