name: Continuous Integration
on: [push, pull_request]

jobs:
  build:
    name: Run all tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Build project
        run: |
          docker build --tag=frontend_build frontend
          docker-compose -f ops/docker-compose.yml -p app build
      - name: Run frontend tests
        run: docker run --rm -t -e CI=true frontend_build npm test
      - name: Run api tests
        run: docker run --rm -t app_api npm test
