name: Continuous Integration
on: [push, pull_request]

jobs:
  build:
    name: Run all tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Build project
        run: ./build.sh
      - name: Run tests
        run: ./test.sh
